export const routerAbi = [
  {
    inputs: [],
    name: "BURN_ADDRESS",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "burnRatio",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "forToken",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fundRatio",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fundWallet",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "from", type: "address" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "message", type: "string" },
    ],
    name: "transferWithDistribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "from", type: "address" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
      { name: "message", type: "string" },
    ],
    name: "transferWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { indexed: true, name: "from", type: "address" },
      { indexed: true, name: "recipient", type: "address" },
      { indexed: false, name: "totalAmount", type: "uint256" },
      { indexed: false, name: "fundAmount", type: "uint256" },
      { indexed: false, name: "burnAmount", type: "uint256" },
      { indexed: false, name: "recipientAmount", type: "uint256" },
      { indexed: false, name: "message", type: "string" },
    ],
    name: "TransferWithDistribution",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "changedBy", type: "address" },
      { indexed: false, name: "fundRatio", type: "uint256" },
      { indexed: false, name: "burnRatio", type: "uint256" },
      { indexed: false, name: "recipientRatio", type: "uint256" },
    ],
    name: "DistributionRatioUpdated",
    type: "event",
  },
] as const;
